[package]
name = "polylabel"
version = "1.0.38"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
description = "A Rust implementation of the Polylabel algorithm"
readme = "README.md"
keywords = ["geo", "polylabel", "gis"]
repository = "https://github.com/urschrei/polylabel-rs"
license = "MIT"

[dependencies]
libc = "0.2.15"
geo = "0.4.5"
num-traits = "0.1"

[lib]
name = "polylabel"
crate-type = ["rlib", "cdylib"]
test = true
doctest = false
doc = true

[profile.release]
rpath = true
lto = true
