[package]
name = "polylabel"
version = "1.1.0"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
description = "A Rust implementation of the Polylabel algorithm for finding optimum polygon label positions."
readme = "README.md"
keywords = ["geo", "polylabel", "gis"]
repository = "https://github.com/urschrei/polylabel-rs"
license = "MIT"

[dependencies]
libc = "0.2.29"
geo = "0.8.3"
geo-types = "0.1.0"
num-traits = "0.1"

[lib]
name = "polylabel"
crate-type = ["rlib", "cdylib"]
test = true
doctest = false
doc = true

[profile.release]
rpath = true
lto = true
