[package]
name = "polylabel"
version = "1.3.1"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
description = "A Rust implementation of the Polylabel algorithm for finding optimum polygon label positions."
readme = "README.md"
keywords = ["geo", "polylabel", "gis"]
repository = "https://github.com/urschrei/polylabel-rs"
license = "MIT"
edition = "2018"
# build = "src/build.rs"

[dependencies]
libc = "0.2.29"
geo = "0.12.2"
num-traits = "0.2.8"

[build-dependencies]
cbindgen = "0.9.0"

[lib]
name = "polylabel"
crate-type = ["rlib", "cdylib"]
test = true
doctest = false
doc = true

[profile.release]
rpath = true
lto = true
